<?php
namespace Ecole2Nat\Admin\Pages;
use Ecole2Nat\Admin\Deletion\DeletionController;
use Ecole2Nat\Distribution\DistributionService;
if (!defined('ABSPATH')) { exit; }
final class DistributionPage
{
    public function __construct(private ?DistributionService $service=null){$this->service??=new DistributionService();}
    public function render():void
    {
        if(!current_user_can('manage_options'))wp_die(esc_html__('Accès refusé.','ecole2nat'));
        $id=absint($_GET['distribution_id']??0);$creating=isset($_GET['action'])&&$_GET['action']==='new';$error='';
        if(isset($_POST['e2n_save_distribution'])){check_admin_referer('e2n_save_distribution_'.$id);$result=$this->service->save($id,sanitize_text_field(wp_unslash($_POST['name']??'')),sanitize_text_field($_POST['start_date']??''),sanitize_text_field($_POST['end_date']??''),(array)($_POST['swimmer_ids']??[]),get_current_user_id());if($result['success']){wp_safe_redirect(admin_url('admin.php?page=ecole2nat-distributions'));exit;}$error=$result['message'];$creating=$id===0;}
        echo '<div class="wrap"><h1>'.esc_html__('Distributions','ecole2nat').'</h1>';if($error!=='')echo '<div class="notice notice-error"><p>'.esc_html($error).'</p></div>';
        if($id>0||$creating)$this->form($id);else $this->list();echo '</div>';
    }
    private function list():void
    {
        echo '<p><a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=ecole2nat-distributions&action=new')).'">'.esc_html__('Créer une distribution','ecole2nat').'</a></p><table class="widefat striped"><thead><tr><th>'.esc_html__('Nom','ecole2nat').'</th><th>'.esc_html__('Période','ecole2nat').'</th><th>'.esc_html__('Avancement','ecole2nat').'</th><th></th></tr></thead><tbody>';
        $rows=$this->service->adminList();foreach($rows as $row){$edit=admin_url('admin.php?page=ecole2nat-distributions&distribution_id='.(int)$row['id']);$delete=DeletionController::url('distribution',(int)$row['id'],admin_url('admin.php?page=ecole2nat-distributions'));echo '<tr><td><strong>'.esc_html($row['name']).'</strong></td><td>'.esc_html(wp_date('d/m/Y',strtotime($row['start_date'])).' — '.wp_date('d/m/Y',strtotime($row['end_date']))).'</td><td>'.esc_html(sprintf(__('%1$d distribués sur %2$d','ecole2nat'),$row['delivered_count'],$row['target_count'])).'</td><td><a href="'.esc_url($edit).'">'.esc_html__('Modifier','ecole2nat').'</a> | <a href="'.esc_url($delete).'" style="color:#b32d2e" onclick="return confirm(\''.esc_js(__('Supprimer cette distribution et tout son historique ?','ecole2nat')).'\')">'.esc_html__('Supprimer','ecole2nat').'</a></td></tr>';}
        if($rows===[])echo '<tr><td colspan="4">'.esc_html__('Aucune distribution.','ecole2nat').'</td></tr>';echo '</tbody></table>';
    }
    private function form(int $id):void
    {
        $row=$id>0?$this->service->find($id):null;if($id>0&&$row===null){echo '<p>'.esc_html__('Distribution introuvable.','ecole2nat').'</p>';return;}$row??=['name'=>'','start_date'=>wp_date('Y-m-d'),'end_date'=>wp_date('Y-m-d')];$selected=array_flip($id>0?$this->service->targetIds($id):[]);$swimmers=$this->service->selectableSwimmers();$categories=[];$groups=[];foreach($swimmers as $s){$categories[(int)$s['category_id']]=$s['category_name'];$groups[(int)$s['group_id']]=$s['group_name'];}asort($categories);asort($groups);
        ?><form method="post" data-e2n-distribution-form><?php wp_nonce_field('e2n_save_distribution_'.$id);?><table class="form-table"><tr><th><label for="e2n-distribution-name"><?php esc_html_e('Nom','ecole2nat');?></label></th><td><input class="regular-text" id="e2n-distribution-name" name="name" value="<?php echo esc_attr($row['name']);?>" required></td></tr><tr><th><?php esc_html_e('Période','ecole2nat');?></th><td><input type="date" name="start_date" value="<?php echo esc_attr($row['start_date']);?>" required> — <input type="date" name="end_date" value="<?php echo esc_attr($row['end_date']);?>" required></td></tr></table>
        <h2><?php esc_html_e('Nageurs concernés','ecole2nat');?></h2><div class="e2n-distribution-filters" style="display:flex;gap:10px;flex-wrap:wrap;margin-bottom:12px"><select data-e2n-distribution-category><option value=""><?php esc_html_e('Toutes les catégories','ecole2nat');?></option><?php foreach($categories as $key=>$label):?><option value="<?php echo (int)$key;?>"><?php echo esc_html($label);?></option><?php endforeach;?></select><select data-e2n-distribution-group><option value=""><?php esc_html_e('Tous les créneaux','ecole2nat');?></option><?php foreach($groups as $key=>$label):?><option value="<?php echo (int)$key;?>"><?php echo esc_html($label);?></option><?php endforeach;?></select><input type="search" placeholder="<?php esc_attr_e('Nom ou prénom','ecole2nat');?>" data-e2n-distribution-search><button type="button" class="button" data-e2n-distribution-check><?php esc_html_e('Tout cocher (résultats)','ecole2nat');?></button><button type="button" class="button" data-e2n-distribution-uncheck><?php esc_html_e('Tout décocher (résultats)','ecole2nat');?></button></div><div data-e2n-distribution-swimmers style="display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:8px;max-height:480px;overflow:auto;padding:10px;border:1px solid #ccd0d4;background:#fff"><?php foreach($swimmers as $s):$search=remove_accents(mb_strtolower($s['first_name'].' '.$s['last_name']));?><label data-category="<?php echo (int)$s['category_id'];?>" data-group="<?php echo (int)$s['group_id'];?>" data-search="<?php echo esc_attr($search);?>"><input type="checkbox" name="swimmer_ids[]" value="<?php echo (int)$s['id'];?>" <?php checked(isset($selected[(int)$s['id']]));?>> <strong><?php echo esc_html($s['first_name'].' '.$s['last_name']);?></strong><br><small><?php echo esc_html($s['group_name']);?></small></label><?php endforeach;?></div><?php submit_button(__('Enregistrer','ecole2nat'),'primary','e2n_save_distribution');?></form><p><a href="<?php echo esc_url(admin_url('admin.php?page=ecole2nat-distributions'));?>">← <?php esc_html_e('Retour','ecole2nat');?></a></p>
        <script>(function(){var f=document.querySelector('[data-e2n-distribution-form]');if(!f)return;var c=f.querySelector('[data-e2n-distribution-category]'),g=f.querySelector('[data-e2n-distribution-group]'),q=f.querySelector('[data-e2n-distribution-search]'),rows=[].slice.call(f.querySelectorAll('[data-search]'));function filter(){var needle=(q.value||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');rows.forEach(function(r){r.hidden=!!((c.value&&r.dataset.category!==c.value)||(g.value&&r.dataset.group!==g.value)||(needle&&r.dataset.search.indexOf(needle)<0));});}c.onchange=g.onchange=q.oninput=filter;function mark(value){rows.forEach(function(r){if(!r.hidden)r.querySelector('input').checked=value;});}f.querySelector('[data-e2n-distribution-check]').onclick=function(){mark(true)};f.querySelector('[data-e2n-distribution-uncheck]').onclick=function(){mark(false)};}());</script><?php
    }
}
